steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - marketplace-db-provisioning-fn
      - --region=us-east1
      - --source=.
      - --trigger-http