steps:
  # Build and deploy the function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - marketplace-db-provisioning-fn
      - --source=.
      - --entry-point=com.andevs.marketplace.function.HelloWorldFunction
      - --runtime=java17
      - --trigger-topic=your-topic-name
      - --region=us-central1
      - --memory=512MB
      - --timeout=540s
      - --set-env-vars=FUNCTION_SIGNATURE_TYPE=event

options:
  logging: CLOUD_LOGGING_ONLY 