# cloudbuild.yaml
steps:
  # 1. Compilar y empaquetar el JAR
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']

  # 2. Desplegar la función (2ª gen) con trigger CloudEvents sobre Firestore
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy "${_FUNCTION_NAME}" \
          --gen2 \
          --region="${_REGION}" \
          --trigger-location="${_REGION}" \
          --runtime="java17" \
          --source="." \
          --entry-point="${_ENTRY_POINT}" \
          --trigger-event-filters="type=google.cloud.firestore.document.v1.created" \
          --trigger-event-filters="database=${_DATABASE_NAME}" \
          --trigger-event-filters-path-pattern="document=${_DOCUMENT_PATH}" \
          --allow-unauthenticated \
          --quiet

# Parámetros personalizables
substitutions:
  _FUNCTION_NAME:   marketplace-db-provisioning-fn
  _REGION:          us-east1
  _ENTRY_POINT:     com.andevs.marketplace.function.DBProvisioningFunction
  _DATABASE_NAME:   db-marketplace
  _DOCUMENT_PATH:   db-provisioning-requests/{docId}

# Para evitar el error de tener service_account sin bucket de logs
options:
  logging: CLOUD_LOGGING_ONLY

# Timeout extendido a 10 minutos
timeout: '600s'